// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('classyInitScopeTest', ['classy', 'classy-initScope']);

  app.classy.controller({
    name: 'InitController',
    inject: ['$scope'],
    initScope: function() {
      return {
        a: 'a',
        b: 'b',
        c: 'c',
        objectA: {
          item1: 1,
          item2: 2
        }
      };
    }
  });

  app.classy.controller({
    name: 'InitWithObjectController',
    inject: ['$scope'],
    initScope: {
      a: 'a',
      b: 'b',
      c: 'c',
      objectA: {
        item1: 1,
        item2: 2
      }
    }
  });

  describe('Classy initScope (classy-initScope.coffee)', function() {
    var initController, initObjectController, objectScope, scope;
    beforeEach(module('classyInitScopeTest'));
    initController = null;
    initObjectController = null;
    scope = null;
    objectScope = null;
    beforeEach(function() {
      inject(function($controller, $rootScope) {
        scope = $rootScope.$new();
        objectScope = $rootScope.$new();
        initController = $controller('InitController', {
          $scope: scope
        });
        initObjectController = $controller('InitWithObjectController', {
          $scope: objectScope
        });
      });
    });
    it('should initialize scope values when initScope is a function', function() {
      expect(scope.a).toBe('a');
      expect(scope.b).toBe('b');
      expect(scope.c).toBe('c');
      expect(scope.objectA).toEqual({
        item1: 1,
        item2: 2
      });
    });
    it('should initialize scope values when initScope is an object', function() {
      expect(objectScope.a).toBe('a');
      expect(objectScope.b).toBe('b');
      expect(objectScope.c).toBe('c');
      expect(objectScope.objectA).toEqual({
        item1: 1,
        item2: 2
      });
    });
  });

}).call(this);
